#!/usr/bin/env python3
"""
Iteration 001 Compiler - Baseline
Direction: baseline-handcrafted-yaml
Strategy: Direct structural mapping from YAML to BSV

Reads YAML files and generates BSV code via template-based translation.
No LLM involvement in this baseline - purely mechanical translation.
"""

import yaml
import sys
import os
from pathlib import Path

def compile_typedefs(yaml_path, output_dir):
    """Read YAML and generate BSV typedef file."""
    with open(yaml_path, 'r') as f:
        data = yaml.safe_load(f)

    module_name = data['meta']['name']
    knowledge = data.get('knowledge', {}).get('bsv', {})
    imports = knowledge.get('imports', [])
    types = data.get('types', [])

    lines = []
    # File header
    lines.append(f"// Generated by Compiler Iteration 001")
    lines.append(f"// Source YAML: {yaml_path}")
    lines.append("")

    # Imports
    for imp in imports:
        lines.append(f"import {imp} :: *;")
    if imports:
        lines.append("")

    # Description comment
    desc = data['meta'].get('description', '').strip()
    if desc:
        for line in desc.split('\n'):
            lines.append(f"// {line.strip()}")
        lines.append("")

    # Typedefs
    for t in types:
        bsv = t.get('bsv_typedef', '')
        if bsv:
            lines.append(bsv + ";")
        else:
            # Fallback: generate from id and value
            tid = t['id']
            lines.append(f"// TODO: {tid} - {t.get('description', '')}")

    content = '\n'.join(lines) + '\n'

    # Write output
    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, f"{module_name}.bsv")
    with open(output_file, 'w') as f:
        f.write(content)

    print(f"Generated: {output_file}")
    return output_file

def main():
    if len(sys.argv) < 2:
        print("Usage: compiler.py <yaml_file> [output_dir]")
        sys.exit(1)

    yaml_file = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "./generated"

    compile_typedefs(yaml_file, output_dir)

if __name__ == "__main__":
    main()
